### ISSUE TITLE
Definitions of crimes are self-referential

### ISSUE THREAD

**Issue by naconner** [liberland/laws#1]
These crimes are self-referential in their definitions:

> Terrorism is intentionally committing an act of terrorism [...]
> 
> Hijacking is intentionally hijacking [...]
> 
> Forgery is forging [...]
> 
> Damage to property is causing damage to the property [...]
> 
> [Assault:] Infliction of bodily harm is inflicting bodily harm [...]
> 
> Polluting environment is causing pollution [...]
> 
> Assisting in committing a criminal offence is assisting another person in committing another criminal offence [...]
> 
> Attempting to commit a criminal offence is attempting to commit another criminal offence [...]

They will need to be sufficiently defined in order to be understandable and enforceable.

**Comment by KacperZajc** [comment]
these offences will be defined precisely in the future, this is just a provisional code for the purposes of going to Liberland now :)

**Comment by naconner** [comment]
I understand what you're saying, and the need to have a basic code in place. It's a good start, however, in any court of law, these should be void for vagueness:

https://en.wikipedia.org/wiki/Void_for_vagueness

Someone accused of any of these crimes has no definition of the *actus reus* that they must defend themselves as not guilty of having commited.

The crime becomes whatever the prosecution deems it to be at the time (as there's also no case law yet established). Thus, we may resonably doubt that the defendant had *mens rea* because it was not possible for them to know the particular act was unlawful.

It can establish a precedent, and for those eager to assist with being the first settlers, being subject to a drumhead court-martial isn't a compelling thought.

That said, to the degree which I feel comfortable with legal definitions, I'll make a pull request, though it would be great to receive more input from legal scholars.

**Comment by KacperZajc** [comment]
no need to convince me, I will make it more precise in some time, leave it for now please :)

**Comment by Jean-LouisMesic** [comment]
Where are the crimes even listed?

**Comment by michalptacnik** [comment]
Drafting a new Criminal Law (will open an issue about it ASAP). Closing the issue, the new law will NOT contain self-referencing clauses.
