### ISSUE TITLE
Unnecessary crimes

### ISSUE THREAD

**Issue by naconner** [liberland/laws#2]
At least two crimes are unnecessary: forgery and terrorism.

In the former, it's already an act of fraud, except with a different victim: the State. Is the intention to apply a different punishment because a state organ is defrauded? If so, this would be a double standard.

Terrorism is an act of aggression, punishable as any combination of other crimes involving the initiation of force (murder, hijacking, theft, etc.). Is the point to have a broader definition than that which is covered by these existing crimes? If there is an element of terrorism that is not an act of aggression, then this is an issue as the charge could be applied to elements which should not be crimes, such as exercising freedom of speech ('thoughtcrime'). 

However, these need to be defined first (see #1) to have a productive discussion on them.

**Comment by manchfu** [comment]
+1

**Comment by KacperZajc** [comment]
done
