### ISSUE TITLE
Business development law permission?

### ISSUE THREAD

**Issue by jonathancross** [liberland/laws#35]
Is it an error that the [Business Development Law](https://docs.google.com/document/d/1F-HBduCHEahdMn6a2XZAwjtSog4axq1B8FRg4k9G2OA/edit) document is read protected by default?
It seems it should be readable by anyone, no?

**Comment by michalptacnik** [comment]
It should, and it will be when there is anything in that document. :) It is now a placeholder, it still needs to be developed, stay tuned! I am sorry for the confusion.
