### ISSUE TITLE
Citizenship law

### ISSUE THREAD

**Issue by hazzik** [liberland/laws#5]
There is a need to have a law which will regulate at least these citizenship questions:
1. How the citizenship can be obtained.
2. How a person can renounce his/her citizenship.
3. Dual/trial/etc citizenship

**Comment by Jean-LouisMesic** [comment]
This will be solved in time, the primary objective for now is constitutionality.

**Comment by michalptacnik** [comment]
Citizenship law drafted here: https://docs.google.com/document/d/1J2o5N9JDOzBXRkefe9Azm6P6vAwqCxw7B2jcKoHSjhg/edit
Please add your recommendations there, google is better for drafting like this than github (markup is not OK). Please reopen issue in case of more questions!
